DROP TABLE IF EXISTS Polls CASCADE;

CREATE TABLE polls (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(200) NOT NULL,
  description VARCHAR(350) NOT NULL,
  poll_link VARCHAR(350) NOT NULL,
  results_link VARCHAR(350) NOT NULL
);
