DROP TABLE IF EXISTS submission CASCADE;

CREATE TABLE submission (
  id SERIAL PRIMARY KEY NOT NULL,
  poll_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  activity VARCHAR(350) NOT NULL,
  rating INTEGER  NOT NULL DEFAULT 0
);
